describe('Sanity Test',
    {
        viewportHeight: 1000,
        viewportWidth: 1650,
    }, () => {
        it('Custom Page', () => {
            cy.visit("https://www.outlookindia.com/plugin-play/2023%EB%85%84-11%EC%9B%94-%EB%A9%94%EC%9D%B4%EC%A0%80-%ED%86%A0%ED%86%A0%EC%82%AC%EC%9D%B4%ED%8A%B8-%EC%88%9C%EC%9C%84-%EC%B6%94%EC%B2%9C-%ED%86%A0%ED%86%A0-%EC%95%88%EC%A0%84%EB%86%80%EC%9D%B4%ED%84%B0-top15-news-332207?show_io_vanish_ads=1")
            cy.contains('Hema')
            cy.wait(2000)

            cy.visit("https://www.outlookindia.com/outlookhub/%EC%B9%B4%EB%93%9C%EA%B9%A1-5%EA%B0%80%EC%A7%80-%EC%9C%A0%ED%98%95%EA%B3%BC-%EC%B2%98%EB%B2%8C-%ED%94%BC%ED%95%B4-%EC%98%88%EB%B0%A9-%EB%B0%A9%EB%B2%95%EC%B6%94%EC%B2%9C-%EC%97%85%EC%B2%B4-%EB%93%B1?show_io_vanish_ads=1")
            cy.contains('Bhoomi Saxena')
            cy.wait(2000)
         })

        it('Redirection page', () => {
            cy.visit("https://www.outlookindia.com/amp/story/national/farmers-protest-then-and-now-how-dilli-chalo-march-is-different-from-earlier-farm-bill-agitation")
            cy.contains('March Is Different From Earlier Farm Law Agitation')
            cy.wait(2000)

            cy.visit("https://www.outlookindia.com/business-spotlight/innovating-workspace-dynamics")
            cy.contains('Hub4Business')
            cy.wait(2000)
        })

        it('Magazine page', () => {
            cy.visit("https://www.outlookindia.com/magazine")
            cy.contains('ALL ISSUES')
            cy.get('#select-mag').select('2023')
            cy.get('#sub-tab-pane-All-02023 > .row > [data-test-id="current-issue-1"] > .magazine-cover-image-m_image__3-ZtB > a > .qt-image').click()
            cy.get('.col-5 > .article-img-box > a > .article-img').click()
            cy.go('back')
            cy.get(':nth-child(1) > .article-img-box > a > .article-img').click()
            cy.go('back')
        })

        it('Weekender page', () => {
            cy.visit("https://www.outlookindia.com/weekender")
            cy.contains('Back to Home')
            cy.get('#section0 > .fp-tableCell > a > .card_layout > .__right').click()
            cy.go('back')
            cy.get('.btn-down > a > img').click()
            cy.wait(1000)
            cy.get('.btn-home').click()
        })

        it('Topic page', () => {
            cy.visit("https://www.outlookindia.com/topic")
            cy.get('[href="https://www.outlookindia.com/topic/sunrisers-hyderabad"]').click()
            cy.contains('Indian Premier League')
            cy.get('#shower').click()
            cy.get(':nth-child(1) > .articles > .row > .col-4 > .article-img-box > a > .article-img').click()
            cy.contains('MOST POPULAR')
            cy.go('back')
            cy.get('#load-more-button-topic').click()
            cy.contains('Related Stories')
            cy.get('#load-more-button-topic').click()
            cy.contains('Related Stories')
        })

        it('National page', () => {
            cy.visit("https://www.outlookindia.com/national")
            cy.contains('POPULAR')
            cy.get('.br-grey > .articles > .row > .order-1 > .article-img-box > a > .article-img').click()
            cy.contains('MOST POPULAR')
            cy.go('back')
            cy.get(':nth-child(2) > .font-size-1').click()
            cy.contains('MOST POPULAR')
            cy.go('back')
            cy.get('.rm-container > .slider-one1 > .slick-next').click()
            cy.get('.rm-container > .slider-one1 > .slick-prev').click()
            cy.wait(1000)
            cy.get('.slider-more-red').click()
            cy.contains('National Web Stories')
            cy.go('back')
            cy.get('.mt-4.rm-container > .article-hero-list > :nth-child(1) > :nth-child(1) > :nth-child(1) > .articles > .row > .col-4 > .article-img-box > a > .article-img').click()
            cy.contains('MOST POPULAR')
            cy.go('back')
            cy.get('section.slider-bg > .rm-container > .category-head-white > .more > a').click()
            cy.contains('National Photo')
            cy.get('#load-more-button-category').click({ force: true })
            cy.contains('National Photo')
            cy.go('back')
            cy.go('back')
            cy.get('.row > .slider-one1 > .slick-next').click()
            cy.get('.row > .slider-one1 > .slick-prev').click()
            cy.get('.rm-bt-section > .article-hero-list > :nth-child(1) > :nth-child(1) > :nth-child(1) > .articles > .row > .col-4 > .article-img-box > a > .article-img').click()
            cy.contains('MOST POPULAR')
            cy.go('back')
            cy.get('#load-more-button-category').click()
            cy.contains('BY')
            cy.get(':nth-child(1) > .articles > .row > .col-4 > .article-img-box > a > .article-img').click()
        })

        it('International page', () => {
            cy.visit("https://www.outlookindia.com/international")
            cy.get('.br-grey > .articles > .row > .order-1 > .article-img-box > a > .article-img').click()
            cy.contains('MOST POPULAR')
            cy.go('back')
            cy.wait(2000)
            cy.get(':nth-child(2) > .font-size-1').click()
            cy.contains('MOST POPULAR')
            cy.go('back')
            cy.wait(2000)
            cy.get('.category-head-two > .more > .slider-more-red').click()
            cy.contains('World Trending')
            cy.go('back')
            cy.wait(2000)
            cy.get('.category-head-white > .more > .slider-more-red').click()
            cy.go('back')
            cy.wait(2000)
            cy.get('.mt-4.elections-ls > .article-hero-list > :nth-child(1) > :nth-child(1) > :nth-child(1) > .articles > .row > .col-4 > .article-img-box > a > .article-img').click()
            cy.contains('Updated on:')
            cy.go('back')
            cy.get('section.slider-bg > .rm-container > .category-head-white > .more > a').click()
            cy.contains('International Photo')
            cy.go('back')
            cy.wait(2000)
            cy.get('.rm-bt-section > .article-hero-list > :nth-child(1) > :nth-child(1) > :nth-child(1) > .articles > .row > .col-4 > .article-img-box > a > .article-img').click()
            cy.contains('Updated on:')
        })

        it('International LMS', () => {
            cy.visit("https://www.outlookindia.com/international")
            cy.get('#load-more-button-category').click()
            cy.contains('International')
            cy.get(':nth-child(1) > .articles > .row > .col-4 > .article-img-box > a > .article-img').click()
            cy.contains('Updated on:')
            cy.go('back')
            cy.wait(2000)
            cy.get('#load-more-button-category').click()
            cy.contains('International')
        })

        it('US page', () => {
            cy.visit("https://www.outlookindia.com/international/us")
            cy.contains('World Trending')
            cy.get('.br-grey > .articles > .row > .order-1 > .article-img-box > a > .article-img').click()
            cy.contains('MOST POPULAR')
            cy.go('back')
            cy.get(':nth-child(2) > .font-size-1').click()
            cy.contains('MOST POPULAR')
            cy.go('back')
            cy.get('.slider-more-red').click()
            cy.contains('World Trending Web Stories')
            cy.get('#load-more-button-category').click()
            cy.contains('World Trending Web Stories')
            cy.go('back')
            cy.go('back')
            cy.get(':nth-child(1) > :nth-child(1) > :nth-child(1) > .articles > .row > .col-4 > .article-img-box > a > .article-img').click()
            cy.contains('MOST POPULAR')
            cy.go('back')
            cy.get(':nth-child(2) > :nth-child(1) > .articles > .row > .col-4 > .article-img-box > a > .article-img').click()
            cy.contains('MOST POPULAR')
            cy.go('back')
            cy.get('#load-more-button-category').click()
            cy.contains('US')
            cy.get('#load-more-button-category').click()
            cy.contains('US')
        })

        it('Election page', () => {
            cy.visit("https://www.outlookindia.com/elections")
            cy.contains('Lok Sabha Elections 2024')
            cy.get(':nth-child(2) > .br-grey > .article-hero-list > :nth-child(1) > .articles > .row > .col-4 > .article-img-box > a > .article-img').click()
            cy.contains('MOST POPULAR')
            cy.go('back')
            cy.get('#load-more-button-category').click()
            cy.get(':nth-child(4) > :nth-child(1) > :nth-child(1) > .articles > .row > .col-4 > .article-img-box > a > .article-img').click()
            cy.contains('MOST POPULAR')
            cy.go('back')
        })

        it('Web-Stories', () => {
            cy.visit("https://www.outlookindia.com/collection/web-stories")
            cy.contains('Web Stories Home')
            cy.get(':nth-child(1) > .articles > .row > .col-4 > .article-img-box > a > .article-img').click()
            cy.get('.i-amphtml-story-fwd-next').click()
            cy.get('.i-amphtml-story-fwd-next').click()
            cy.wait(1000)
            cy.get('.i-amphtml-story-back-prev').click()
            cy.get('.i-amphtml-story-back-prev').click()
            cy.go('back')
            cy.get('#load-more-button-category').click()
            cy.contains('Web Stories Home')
            cy.get('#load-more-button-category').click()
            cy.contains('Web Stories Home')
        })

        it('Photo and video page', () => {
            cy.visit("https://www.outlookindia.com/collection/mediahub-home")
            cy.contains('Media Hub')
            cy.get(':nth-child(1) > .articles > .row > .col-4 > .article-img-box > a > .article-img').click()
            cy.contains('MOST POPULAR')
            cy.go('back')
            cy.get('#load-more-button-category').click()
            cy.contains('Media Hub')
            cy.get(':nth-child(1) > .articles > .row > .col-4 > .article-img-box > a > .article-img').click()
            cy.contains('MOST POPULAR')
            cy.go('back')
            cy.get('#load-more-button-category').click()
            cy.contains('Media Hub')
            cy.visit("https://www.outlookindia.com/nazarya/can-money-really-buy-happiness-hilarious-reactions-from-delhis-hauz-khas")
            cy.contains('MOST POPULAR')
            cy.get('.ss-next > img').click()
            cy.wait(1000)
            cy.get('.ss-prev > img').click()
        })



        Cypress.on('uncaught:exception', (err, runnable) => {
            return false
        })
    })